name: Test

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo SHA: is ${{ github.sha }}
          echo Ref: is ${{ github.ref }}
          
      - name: Generate My README
        run: |
           sed -i 's/${NAME}/${{ env.SECRET_NAME }}/g' README.md
           export CONTENT=$(cat README.md)
        env:
          SECRET_NAME: ${{secrets.NAME}}

      - name: Notify in slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: random
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://avatars3.githubusercontent.com/u/2242350?s=60&v=4
          SLACK_MESSAGE: '${{ env.CONTENT }}'
          SLACK_TITLE: Random
          SLACK_USERNAME: arun
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
